services:
  app:
    build: .
    container_name: page-s5vectrs
    restart: unless-stopped
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.page-s5vectrs.rule=Host(`kalina.pavlin.dev`)"
      - "traefik.http.routers.page-s5vectrs.entrypoints=web"
      - "traefik.http.services.page-s5vectrs.loadbalancer.server.port=3000"
    networks:
      - web

networks:
  web:
    external: true
